SELECT 
    SDSD_NAME,
    BRKS_CALL_SYS_NAME,
    BRKS_SYS_RETURN_CODE,
    BRKS_APP_RETURN_CODE,
    AVG(DATEDIFF(MILLISECOND, BRKS_BRKR_BEG_DTM, BRKS_BRKR_END_DTM)) AS avg_in_ms,
    MIN(DATEDIFF(MILLISECOND, BRKS_BRKR_BEG_DTM, BRKS_BRKR_END_DTM)) AS MIN_in_ms,
    MAX(DATEDIFF(MILLISECOND, BRKS_BRKR_BEG_DTM, BRKS_BRKR_END_DTM)) AS MAX_in_ms,
    COUNT(*) AS [Count]
FROM facets.CER_BRKS_BROKER_STATS
WHERE 
    BRKS_BRKR_BEG_DTM > DATEADD(DAY, -1, GETDATE())
GROUP BY 
    SDSD_NAME, 
    BRKS_CALL_SYS_NAME, 
    BRKS_SYS_RETURN_CODE, 
    BRKS_APP_RETURN_CODE;